// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package assignment1.models.protobuf;

public interface Data_protoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data_proto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Data_proto.Owner_proto owners = 1;</code>
   */
  java.util.List<assignment1.models.protobuf.Data_proto.Owner_proto> 
      getOwnersList();
  /**
   * <code>repeated .Data_proto.Owner_proto owners = 1;</code>
   */
  assignment1.models.protobuf.Data_proto.Owner_proto getOwners(int index);
  /**
   * <code>repeated .Data_proto.Owner_proto owners = 1;</code>
   */
  int getOwnersCount();
  /**
   * <code>repeated .Data_proto.Owner_proto owners = 1;</code>
   */
  java.util.List<? extends assignment1.models.protobuf.Data_proto.Owner_protoOrBuilder> 
      getOwnersOrBuilderList();
  /**
   * <code>repeated .Data_proto.Owner_proto owners = 1;</code>
   */
  assignment1.models.protobuf.Data_proto.Owner_protoOrBuilder getOwnersOrBuilder(
      int index);
}
