// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Owner_and_Pet.proto

package assignment1.models.protobuf;

/**
 * Protobuf type {@code protobuf.Owner_proto}
 */
public final class Owner_proto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.Owner_proto)
    Owner_protoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Owner_proto.newBuilder() to construct.
  private Owner_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Owner_proto() {
    name_ = "";
    address_ = "";
    pets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Owner_proto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Owner_proto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            ownerId_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = birthdate_.toBuilder();
            }
            birthdate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(birthdate_);
              birthdate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            telephone_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            address_ = bs;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              pets_ = new java.util.ArrayList<assignment1.models.protobuf.Owner_proto.Pet_proto>();
              mutable_bitField0_ |= 0x00000020;
            }
            pets_.add(
                input.readMessage(assignment1.models.protobuf.Owner_proto.Pet_proto.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        pets_ = java.util.Collections.unmodifiableList(pets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            assignment1.models.protobuf.Owner_proto.class, assignment1.models.protobuf.Owner_proto.Builder.class);
  }

  public interface Pet_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Owner_proto.Pet_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 petId = 1;</code>
     * @return Whether the petId field is set.
     */
    boolean hasPetId();
    /**
     * <code>optional int32 petId = 1;</code>
     * @return The petId.
     */
    int getPetId();

    /**
     * <code>optional int32 ownerId = 2;</code>
     * @return Whether the ownerId field is set.
     */
    boolean hasOwnerId();
    /**
     * <code>optional int32 ownerId = 2;</code>
     * @return The ownerId.
     */
    int getOwnerId();

    /**
     * <code>optional string name = 3;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string gender = 4;</code>
     * @return Whether the gender field is set.
     */
    boolean hasGender();
    /**
     * <code>optional string gender = 4;</code>
     * @return The gender.
     */
    java.lang.String getGender();
    /**
     * <code>optional string gender = 4;</code>
     * @return The bytes for gender.
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>optional float weight = 5;</code>
     * @return Whether the weight field is set.
     */
    boolean hasWeight();
    /**
     * <code>optional float weight = 5;</code>
     * @return The weight.
     */
    float getWeight();

    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     * @return Whether the birthdate field is set.
     */
    boolean hasBirthdate();
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     * @return The birthdate.
     */
    com.google.protobuf.Timestamp getBirthdate();
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder();

    /**
     * <code>optional string description = 7;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 7;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 7;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code protobuf.Owner_proto.Pet_proto}
   */
  public static final class Pet_proto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Owner_proto.Pet_proto)
      Pet_protoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pet_proto.newBuilder() to construct.
    private Pet_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pet_proto() {
      name_ = "";
      gender_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pet_proto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pet_proto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              petId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ownerId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              gender_ = bs;
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              weight_ = input.readFloat();
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) != 0)) {
                subBuilder = birthdate_.toBuilder();
              }
              birthdate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthdate_);
                birthdate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              description_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_Pet_proto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_Pet_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              assignment1.models.protobuf.Owner_proto.Pet_proto.class, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder.class);
    }

    private int bitField0_;
    public static final int PETID_FIELD_NUMBER = 1;
    private int petId_;
    /**
     * <code>optional int32 petId = 1;</code>
     * @return Whether the petId field is set.
     */
    @java.lang.Override
    public boolean hasPetId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 petId = 1;</code>
     * @return The petId.
     */
    @java.lang.Override
    public int getPetId() {
      return petId_;
    }

    public static final int OWNERID_FIELD_NUMBER = 2;
    private int ownerId_;
    /**
     * <code>optional int32 ownerId = 2;</code>
     * @return Whether the ownerId field is set.
     */
    @java.lang.Override
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 ownerId = 2;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public int getOwnerId() {
      return ownerId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object gender_;
    /**
     * <code>optional string gender = 4;</code>
     * @return Whether the gender field is set.
     */
    @java.lang.Override
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The bytes for gender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 5;
    private float weight_;
    /**
     * <code>optional float weight = 5;</code>
     * @return Whether the weight field is set.
     */
    @java.lang.Override
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float weight = 5;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp birthdate_;
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     * @return Whether the birthdate field is set.
     */
    @java.lang.Override
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     * @return The birthdate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getBirthdate() {
      return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
      return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 7;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string description = 7;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 7;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, petId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, ownerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, weight_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeMessage(6, getBirthdate());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, petId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ownerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, weight_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getBirthdate());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof assignment1.models.protobuf.Owner_proto.Pet_proto)) {
        return super.equals(obj);
      }
      assignment1.models.protobuf.Owner_proto.Pet_proto other = (assignment1.models.protobuf.Owner_proto.Pet_proto) obj;

      if (hasPetId() != other.hasPetId()) return false;
      if (hasPetId()) {
        if (getPetId()
            != other.getPetId()) return false;
      }
      if (hasOwnerId() != other.hasOwnerId()) return false;
      if (hasOwnerId()) {
        if (getOwnerId()
            != other.getOwnerId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasGender() != other.hasGender()) return false;
      if (hasGender()) {
        if (!getGender()
            .equals(other.getGender())) return false;
      }
      if (hasWeight() != other.hasWeight()) return false;
      if (hasWeight()) {
        if (java.lang.Float.floatToIntBits(getWeight())
            != java.lang.Float.floatToIntBits(
                other.getWeight())) return false;
      }
      if (hasBirthdate() != other.hasBirthdate()) return false;
      if (hasBirthdate()) {
        if (!getBirthdate()
            .equals(other.getBirthdate())) return false;
      }
      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPetId()) {
        hash = (37 * hash) + PETID_FIELD_NUMBER;
        hash = (53 * hash) + getPetId();
      }
      if (hasOwnerId()) {
        hash = (37 * hash) + OWNERID_FIELD_NUMBER;
        hash = (53 * hash) + getOwnerId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getGender().hashCode();
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWeight());
      }
      if (hasBirthdate()) {
        hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
        hash = (53 * hash) + getBirthdate().hashCode();
      }
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static assignment1.models.protobuf.Owner_proto.Pet_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(assignment1.models.protobuf.Owner_proto.Pet_proto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Owner_proto.Pet_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Owner_proto.Pet_proto)
        assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_Pet_proto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_Pet_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                assignment1.models.protobuf.Owner_proto.Pet_proto.class, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder.class);
      }

      // Construct using assignment1.models.protobuf.Owner_proto.Pet_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBirthdateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        petId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ownerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        weight_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (birthdateBuilder_ == null) {
          birthdate_ = null;
        } else {
          birthdateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_Pet_proto_descriptor;
      }

      @java.lang.Override
      public assignment1.models.protobuf.Owner_proto.Pet_proto getDefaultInstanceForType() {
        return assignment1.models.protobuf.Owner_proto.Pet_proto.getDefaultInstance();
      }

      @java.lang.Override
      public assignment1.models.protobuf.Owner_proto.Pet_proto build() {
        assignment1.models.protobuf.Owner_proto.Pet_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public assignment1.models.protobuf.Owner_proto.Pet_proto buildPartial() {
        assignment1.models.protobuf.Owner_proto.Pet_proto result = new assignment1.models.protobuf.Owner_proto.Pet_proto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.petId_ = petId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ownerId_ = ownerId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.weight_ = weight_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          if (birthdateBuilder_ == null) {
            result.birthdate_ = birthdate_;
          } else {
            result.birthdate_ = birthdateBuilder_.build();
          }
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof assignment1.models.protobuf.Owner_proto.Pet_proto) {
          return mergeFrom((assignment1.models.protobuf.Owner_proto.Pet_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(assignment1.models.protobuf.Owner_proto.Pet_proto other) {
        if (other == assignment1.models.protobuf.Owner_proto.Pet_proto.getDefaultInstance()) return this;
        if (other.hasPetId()) {
          setPetId(other.getPetId());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGender()) {
          bitField0_ |= 0x00000008;
          gender_ = other.gender_;
          onChanged();
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasBirthdate()) {
          mergeBirthdate(other.getBirthdate());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000040;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        assignment1.models.protobuf.Owner_proto.Pet_proto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (assignment1.models.protobuf.Owner_proto.Pet_proto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int petId_ ;
      /**
       * <code>optional int32 petId = 1;</code>
       * @return Whether the petId field is set.
       */
      @java.lang.Override
      public boolean hasPetId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 petId = 1;</code>
       * @return The petId.
       */
      @java.lang.Override
      public int getPetId() {
        return petId_;
      }
      /**
       * <code>optional int32 petId = 1;</code>
       * @param value The petId to set.
       * @return This builder for chaining.
       */
      public Builder setPetId(int value) {
        bitField0_ |= 0x00000001;
        petId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 petId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        petId_ = 0;
        onChanged();
        return this;
      }

      private int ownerId_ ;
      /**
       * <code>optional int32 ownerId = 2;</code>
       * @return Whether the ownerId field is set.
       */
      @java.lang.Override
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 ownerId = 2;</code>
       * @return The ownerId.
       */
      @java.lang.Override
      public int getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>optional int32 ownerId = 2;</code>
       * @param value The ownerId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerId(int value) {
        bitField0_ |= 0x00000002;
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ownerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>optional string gender = 4;</code>
       * @return Whether the gender field is set.
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string gender = 4;</code>
       * @return The gender.
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gender = 4;</code>
       * @return The bytes for gender.
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 4;</code>
       * @param value The bytes for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gender_ = value;
        onChanged();
        return this;
      }

      private float weight_ ;
      /**
       * <code>optional float weight = 5;</code>
       * @return Whether the weight field is set.
       */
      @java.lang.Override
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional float weight = 5;</code>
       * @return The weight.
       */
      @java.lang.Override
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>optional float weight = 5;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(float value) {
        bitField0_ |= 0x00000010;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float weight = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        weight_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp birthdate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthdateBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       * @return Whether the birthdate field is set.
       */
      public boolean hasBirthdate() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       * @return The birthdate.
       */
      public com.google.protobuf.Timestamp getBirthdate() {
        if (birthdateBuilder_ == null) {
          return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
        } else {
          return birthdateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public Builder setBirthdate(com.google.protobuf.Timestamp value) {
        if (birthdateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthdate_ = value;
          onChanged();
        } else {
          birthdateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public Builder setBirthdate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (birthdateBuilder_ == null) {
          birthdate_ = builderForValue.build();
          onChanged();
        } else {
          birthdateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public Builder mergeBirthdate(com.google.protobuf.Timestamp value) {
        if (birthdateBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
              birthdate_ != null &&
              birthdate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            birthdate_ =
              com.google.protobuf.Timestamp.newBuilder(birthdate_).mergeFrom(value).buildPartial();
          } else {
            birthdate_ = value;
          }
          onChanged();
        } else {
          birthdateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public Builder clearBirthdate() {
        if (birthdateBuilder_ == null) {
          birthdate_ = null;
          onChanged();
        } else {
          birthdateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBirthdateBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getBirthdateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
        if (birthdateBuilder_ != null) {
          return birthdateBuilder_.getMessageOrBuilder();
        } else {
          return birthdate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp birthdate = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBirthdateFieldBuilder() {
        if (birthdateBuilder_ == null) {
          birthdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBirthdate(),
                  getParentForChildren(),
                  isClean());
          birthdate_ = null;
        }
        return birthdateBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 7;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string description = 7;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 7;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 7;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000040);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Owner_proto.Pet_proto)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Owner_proto.Pet_proto)
    private static final assignment1.models.protobuf.Owner_proto.Pet_proto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new assignment1.models.protobuf.Owner_proto.Pet_proto();
    }

    public static assignment1.models.protobuf.Owner_proto.Pet_proto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Pet_proto>
        PARSER = new com.google.protobuf.AbstractParser<Pet_proto>() {
      @java.lang.Override
      public Pet_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pet_proto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pet_proto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pet_proto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public assignment1.models.protobuf.Owner_proto.Pet_proto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int OWNER_ID_FIELD_NUMBER = 1;
  private int ownerId_;
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return Whether the ownerId field is set.
   */
  @java.lang.Override
  public boolean hasOwnerId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public int getOwnerId() {
    return ownerId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp birthdate_;
  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   * @return The birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getBirthdate() {
    return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
    return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
  }

  public static final int TELEPHONE_FIELD_NUMBER = 4;
  private int telephone_;
  /**
   * <code>optional int32 telephone = 4;</code>
   * @return Whether the telephone field is set.
   */
  @java.lang.Override
  public boolean hasTelephone() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 telephone = 4;</code>
   * @return The telephone.
   */
  @java.lang.Override
  public int getTelephone() {
    return telephone_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETS_FIELD_NUMBER = 6;
  private java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto> pets_;
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  @java.lang.Override
  public java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto> getPetsList() {
    return pets_;
  }
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder> 
      getPetsOrBuilderList() {
    return pets_;
  }
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  @java.lang.Override
  public int getPetsCount() {
    return pets_.size();
  }
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  @java.lang.Override
  public assignment1.models.protobuf.Owner_proto.Pet_proto getPets(int index) {
    return pets_.get(index);
  }
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  @java.lang.Override
  public assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder getPetsOrBuilder(
      int index) {
    return pets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, ownerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getBirthdate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, telephone_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    for (int i = 0; i < pets_.size(); i++) {
      output.writeMessage(6, pets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ownerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBirthdate());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, telephone_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    for (int i = 0; i < pets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, pets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof assignment1.models.protobuf.Owner_proto)) {
      return super.equals(obj);
    }
    assignment1.models.protobuf.Owner_proto other = (assignment1.models.protobuf.Owner_proto) obj;

    if (hasOwnerId() != other.hasOwnerId()) return false;
    if (hasOwnerId()) {
      if (getOwnerId()
          != other.getOwnerId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
    }
    if (hasTelephone() != other.hasTelephone()) return false;
    if (hasTelephone()) {
      if (getTelephone()
          != other.getTelephone()) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getPetsList()
        .equals(other.getPetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOwnerId()) {
      hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    if (hasTelephone()) {
      hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getTelephone();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getPetsCount() > 0) {
      hash = (37 * hash) + PETS_FIELD_NUMBER;
      hash = (53 * hash) + getPetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static assignment1.models.protobuf.Owner_proto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static assignment1.models.protobuf.Owner_proto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static assignment1.models.protobuf.Owner_proto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static assignment1.models.protobuf.Owner_proto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(assignment1.models.protobuf.Owner_proto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.Owner_proto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.Owner_proto)
      assignment1.models.protobuf.Owner_protoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              assignment1.models.protobuf.Owner_proto.class, assignment1.models.protobuf.Owner_proto.Builder.class);
    }

    // Construct using assignment1.models.protobuf.Owner_proto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBirthdateFieldBuilder();
        getPetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ownerId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (birthdateBuilder_ == null) {
        birthdate_ = null;
      } else {
        birthdateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      telephone_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        petsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return assignment1.models.protobuf.OwnerandPet.internal_static_protobuf_Owner_proto_descriptor;
    }

    @java.lang.Override
    public assignment1.models.protobuf.Owner_proto getDefaultInstanceForType() {
      return assignment1.models.protobuf.Owner_proto.getDefaultInstance();
    }

    @java.lang.Override
    public assignment1.models.protobuf.Owner_proto build() {
      assignment1.models.protobuf.Owner_proto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public assignment1.models.protobuf.Owner_proto buildPartial() {
      assignment1.models.protobuf.Owner_proto result = new assignment1.models.protobuf.Owner_proto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ownerId_ = ownerId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (birthdateBuilder_ == null) {
          result.birthdate_ = birthdate_;
        } else {
          result.birthdate_ = birthdateBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.telephone_ = telephone_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.address_ = address_;
      if (petsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          pets_ = java.util.Collections.unmodifiableList(pets_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.pets_ = pets_;
      } else {
        result.pets_ = petsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof assignment1.models.protobuf.Owner_proto) {
        return mergeFrom((assignment1.models.protobuf.Owner_proto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(assignment1.models.protobuf.Owner_proto other) {
      if (other == assignment1.models.protobuf.Owner_proto.getDefaultInstance()) return this;
      if (other.hasOwnerId()) {
        setOwnerId(other.getOwnerId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBirthdate()) {
        mergeBirthdate(other.getBirthdate());
      }
      if (other.hasTelephone()) {
        setTelephone(other.getTelephone());
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      if (petsBuilder_ == null) {
        if (!other.pets_.isEmpty()) {
          if (pets_.isEmpty()) {
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePetsIsMutable();
            pets_.addAll(other.pets_);
          }
          onChanged();
        }
      } else {
        if (!other.pets_.isEmpty()) {
          if (petsBuilder_.isEmpty()) {
            petsBuilder_.dispose();
            petsBuilder_ = null;
            pets_ = other.pets_;
            bitField0_ = (bitField0_ & ~0x00000020);
            petsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPetsFieldBuilder() : null;
          } else {
            petsBuilder_.addAllMessages(other.pets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      assignment1.models.protobuf.Owner_proto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (assignment1.models.protobuf.Owner_proto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ownerId_ ;
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return Whether the ownerId field is set.
     */
    @java.lang.Override
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {
      bitField0_ |= 0x00000001;
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 owner_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ownerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp birthdate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthdateBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     * @return The birthdate.
     */
    public com.google.protobuf.Timestamp getBirthdate() {
      if (birthdateBuilder_ == null) {
        return birthdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
      } else {
        return birthdateBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public Builder setBirthdate(com.google.protobuf.Timestamp value) {
      if (birthdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        birthdate_ = value;
        onChanged();
      } else {
        birthdateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public Builder setBirthdate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (birthdateBuilder_ == null) {
        birthdate_ = builderForValue.build();
        onChanged();
      } else {
        birthdateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public Builder mergeBirthdate(com.google.protobuf.Timestamp value) {
      if (birthdateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            birthdate_ != null &&
            birthdate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          birthdate_ =
            com.google.protobuf.Timestamp.newBuilder(birthdate_).mergeFrom(value).buildPartial();
        } else {
          birthdate_ = value;
        }
        onChanged();
      } else {
        birthdateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public Builder clearBirthdate() {
      if (birthdateBuilder_ == null) {
        birthdate_ = null;
        onChanged();
      } else {
        birthdateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getBirthdateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getBirthdateFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder() {
      if (birthdateBuilder_ != null) {
        return birthdateBuilder_.getMessageOrBuilder();
      } else {
        return birthdate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : birthdate_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getBirthdateFieldBuilder() {
      if (birthdateBuilder_ == null) {
        birthdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getBirthdate(),
                getParentForChildren(),
                isClean());
        birthdate_ = null;
      }
      return birthdateBuilder_;
    }

    private int telephone_ ;
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return Whether the telephone field is set.
     */
    @java.lang.Override
    public boolean hasTelephone() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return The telephone.
     */
    @java.lang.Override
    public int getTelephone() {
      return telephone_;
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @param value The telephone to set.
     * @return This builder for chaining.
     */
    public Builder setTelephone(int value) {
      bitField0_ |= 0x00000008;
      telephone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 telephone = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelephone() {
      bitField0_ = (bitField0_ & ~0x00000008);
      telephone_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }

    private java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto> pets_ =
      java.util.Collections.emptyList();
    private void ensurePetsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        pets_ = new java.util.ArrayList<assignment1.models.protobuf.Owner_proto.Pet_proto>(pets_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        assignment1.models.protobuf.Owner_proto.Pet_proto, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder, assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder> petsBuilder_;

    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto> getPetsList() {
      if (petsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pets_);
      } else {
        return petsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public int getPetsCount() {
      if (petsBuilder_ == null) {
        return pets_.size();
      } else {
        return petsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public assignment1.models.protobuf.Owner_proto.Pet_proto getPets(int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);
      } else {
        return petsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder setPets(
        int index, assignment1.models.protobuf.Owner_proto.Pet_proto value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.set(index, value);
        onChanged();
      } else {
        petsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder setPets(
        int index, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.set(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder addPets(assignment1.models.protobuf.Owner_proto.Pet_proto value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(value);
        onChanged();
      } else {
        petsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder addPets(
        int index, assignment1.models.protobuf.Owner_proto.Pet_proto value) {
      if (petsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePetsIsMutable();
        pets_.add(index, value);
        onChanged();
      } else {
        petsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder addPets(
        assignment1.models.protobuf.Owner_proto.Pet_proto.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder addPets(
        int index, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder builderForValue) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.add(index, builderForValue.build());
        onChanged();
      } else {
        petsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder addAllPets(
        java.lang.Iterable<? extends assignment1.models.protobuf.Owner_proto.Pet_proto> values) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pets_);
        onChanged();
      } else {
        petsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder clearPets() {
      if (petsBuilder_ == null) {
        pets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        petsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public Builder removePets(int index) {
      if (petsBuilder_ == null) {
        ensurePetsIsMutable();
        pets_.remove(index);
        onChanged();
      } else {
        petsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public assignment1.models.protobuf.Owner_proto.Pet_proto.Builder getPetsBuilder(
        int index) {
      return getPetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder getPetsOrBuilder(
        int index) {
      if (petsBuilder_ == null) {
        return pets_.get(index);  } else {
        return petsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public java.util.List<? extends assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder> 
         getPetsOrBuilderList() {
      if (petsBuilder_ != null) {
        return petsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pets_);
      }
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public assignment1.models.protobuf.Owner_proto.Pet_proto.Builder addPetsBuilder() {
      return getPetsFieldBuilder().addBuilder(
          assignment1.models.protobuf.Owner_proto.Pet_proto.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public assignment1.models.protobuf.Owner_proto.Pet_proto.Builder addPetsBuilder(
        int index) {
      return getPetsFieldBuilder().addBuilder(
          index, assignment1.models.protobuf.Owner_proto.Pet_proto.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
     */
    public java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto.Builder> 
         getPetsBuilderList() {
      return getPetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        assignment1.models.protobuf.Owner_proto.Pet_proto, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder, assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder> 
        getPetsFieldBuilder() {
      if (petsBuilder_ == null) {
        petsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            assignment1.models.protobuf.Owner_proto.Pet_proto, assignment1.models.protobuf.Owner_proto.Pet_proto.Builder, assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder>(
                pets_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        pets_ = null;
      }
      return petsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.Owner_proto)
  }

  // @@protoc_insertion_point(class_scope:protobuf.Owner_proto)
  private static final assignment1.models.protobuf.Owner_proto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new assignment1.models.protobuf.Owner_proto();
  }

  public static assignment1.models.protobuf.Owner_proto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Owner_proto>
      PARSER = new com.google.protobuf.AbstractParser<Owner_proto>() {
    @java.lang.Override
    public Owner_proto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Owner_proto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Owner_proto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Owner_proto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public assignment1.models.protobuf.Owner_proto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

