// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Owner_and_Pet.proto

package assignment1.models.protobuf;

public final class OwnerandPet {
  private OwnerandPet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Owner_proto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Owner_proto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Owner_proto_Pet_proto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Owner_proto_Pet_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Owner_and_Pet.proto\022\010protobuf\032\037google/" +
      "protobuf/timestamp.proto\"\317\002\n\013Owner_proto" +
      "\022\020\n\010owner_id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022-\n\tbirt" +
      "hdate\030\003 \001(\0132\032.google.protobuf.Timestamp\022" +
      "\021\n\ttelephone\030\004 \001(\005\022\017\n\007address\030\005 \001(\t\022-\n\004p" +
      "ets\030\006 \003(\0132\037.protobuf.Owner_proto.Pet_pro" +
      "to\032\235\001\n\tPet_proto\022\r\n\005petId\030\001 \001(\005\022\017\n\007owner" +
      "Id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\016\n\006gender\030\004 \001(\t\022\016" +
      "\n\006weight\030\005 \001(\002\022-\n\tbirthdate\030\006 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\023\n\013description\030\007 \001" +
      "(\tB,\n\033assignment1.models.protobufB\013Owner" +
      "andPetP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_protobuf_Owner_proto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Owner_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Owner_proto_descriptor,
        new java.lang.String[] { "OwnerId", "Name", "Birthdate", "Telephone", "Address", "Pets", });
    internal_static_protobuf_Owner_proto_Pet_proto_descriptor =
      internal_static_protobuf_Owner_proto_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Owner_proto_Pet_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Owner_proto_Pet_proto_descriptor,
        new java.lang.String[] { "PetId", "OwnerId", "Name", "Gender", "Weight", "Birthdate", "Description", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
