// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Owner_and_Pet.proto

package assignment1.models.protobuf;

public interface Owner_protoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Owner_proto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return Whether the ownerId field is set.
   */
  boolean hasOwnerId();
  /**
   * <code>optional int32 owner_id = 1;</code>
   * @return The ownerId.
   */
  int getOwnerId();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   * @return Whether the birthdate field is set.
   */
  boolean hasBirthdate();
  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   * @return The birthdate.
   */
  com.google.protobuf.Timestamp getBirthdate();
  /**
   * <code>optional .google.protobuf.Timestamp birthdate = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBirthdateOrBuilder();

  /**
   * <code>optional int32 telephone = 4;</code>
   * @return Whether the telephone field is set.
   */
  boolean hasTelephone();
  /**
   * <code>optional int32 telephone = 4;</code>
   * @return The telephone.
   */
  int getTelephone();

  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  java.util.List<assignment1.models.protobuf.Owner_proto.Pet_proto> 
      getPetsList();
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  assignment1.models.protobuf.Owner_proto.Pet_proto getPets(int index);
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  int getPetsCount();
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  java.util.List<? extends assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder> 
      getPetsOrBuilderList();
  /**
   * <code>repeated .protobuf.Owner_proto.Pet_proto pets = 6;</code>
   */
  assignment1.models.protobuf.Owner_proto.Pet_protoOrBuilder getPetsOrBuilder(
      int index);
}
